openapi: 3.0.0
paths:
  /api:
    get:
      operationId: AppController_getSwagger
      summary: Return Swagger page with API description.
      description: |-
        This is the root endpoint. It is redirected to the swagger page.
        Get swagger page.
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: boolean
  /api/character:
    get:
      operationId: CharacterController_getAllCharacters
      summary: Get all characters, with their nemeses and secrets.
      description: Get all characters, with their nemeses and secrets.
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CharacterDTO'
  /api/nemesis:
    get:
      operationId: NemesisController_getAllNemeses
      summary: Get all nemesis, with their character and secrets.
      description: Get all nemesis, with their character and secrets.
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NemesisDTO'
  /api/secret:
    get:
      operationId: SecretController_getAllSecrets
      summary: Get all secrets, with their nemesis and his character.
      description: Get all secrets, with their nemesis and his character.
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SecretDTO'
  /api/statistics:
    get:
      operationId: StatisticsController_getStatistics
      summary: >-
        Get statistics about characters and nemeses. Return also all characters
        with their nemeses and secrets.
      description: >-
        Get statistics about characters and nemeses. Return also all characters
        with their nemeses and secrets.
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatisticsDTO'
        '404':
          description: Throws an exception if no character or nemesis exists.
info:
  title: Koala API
  description: API description
  version: 0.0.1
  contact: {}
tags: []
servers: []
components:
  schemas:
    CharacterDTO:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        gender:
          type: string
        ability:
          type: string
        minimal_distance:
          type: number
        weight:
          type: number
        born:
          format: date-time
          type: string
        in_space_since:
          format: date-time
          type: string
        beer_consumption:
          type: number
        knows_the_answer:
          type: boolean
        nemesis_list:
          type: array
          items:
            $ref: '#/components/schemas/NemesisDTO'
      required:
        - id
        - name
        - ability
        - minimal_distance
        - born
        - beer_consumption
        - knows_the_answer
    SecretDTO:
      type: object
      properties:
        id:
          type: number
        secret_code:
          type: number
        nemesis_id:
          type: number
        nemesis:
          $ref: '#/components/schemas/NemesisDTO'
      required:
        - id
        - secret_code
        - nemesis_id
    NemesisDTO:
      type: object
      properties:
        id:
          type: number
        isAlive:
          type: boolean
        years:
          type: number
        character_id:
          type: number
        character:
          $ref: '#/components/schemas/CharacterDTO'
        secret_list:
          type: array
          items:
            $ref: '#/components/schemas/SecretDTO'
      required:
        - id
        - isAlive
    StatisticsDTO:
      type: object
      properties:
        count_characters:
          type: number
        average_age_character:
          type: number
        average_weight_characters:
          type: number
        count_live_nemesis:
          type: number
        average_age_nemesis:
          type: number
        count_all:
          type: number
        average_age_all:
          type: number
        gender:
          type: object
        characters:
          type: array
          items:
            $ref: '#/components/schemas/CharacterDTO'
      required:
        - count_characters
        - average_age_character
        - average_weight_characters
        - count_live_nemesis
        - average_age_nemesis
        - count_all
        - average_age_all
        - gender
        - characters
